# Generated by Django 4.2 on 2025-08-23 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveysession',
            old_name='start_time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='value',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='description',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='surveysession',
            name='user',
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('scale', 'Scale'), ('text', 'Text')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question'),
        ),
        migrations.AlterField(
            model_name='response',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveysession'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='survey',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='surveysession',
            name='ip_address',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='surveysession',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey'),
        ),
    ]
